services:
  backend:
    build: ./backend
    environment:
      PORT: "3000"
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3002:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
